= VDI Handler Plugin Script Examples
:icons: font

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This repository contains example implementations of the VDI Plugin Handler
Server's plugin API in various languages.

Each directory under the link:examples[] directory is intended to be a jumping
off point for the development of a VDI plugin.  All that is necessary is to copy
the contents of the target directory (or directories) into a new repository.

For more details about the scripts themselves and their inputs and outputs see
the https://github.com/VEuPathDB/vdi-plugin-handler-server[VDI Plugin Handler Server]
readme.

== Demonstration

Each one of the examples contains a working Dockerfile that can be used to spin
up a working VDI Plugin Handler Server instance.

For convenience, the steps necessary to build and start a working example
container have been provided in the included `makefile`.

=== Prerequisites

* Docker
* sshuttle

=== Setup

. Copy the link:example.env[] file from the root of this repo to a new file
  named `.env`  in the repository root directory. +
  The `.env` file will be ignored by Git by default.
. Edit the new `.env` file by doing the following at minimum:
.. Fill in the `LDAP_SERVER` variable value.
.. Fill in the `ORACLE_BASE_DN` variable value.
.. Fill in the `DB_CONNECTION_LDAP_EXAMPLE` variable value with the TNS name of
   a real VEuPathDB database.
+
NOTE: No connection to any databases will be attempted by the VDI Plugin Handler
Server or any of the included example plugin scripts.  The TNS name is required solely for the LDAP lookup to function.

=== Run an Example

--
. Build the target example docker container by using one of the included `make`
  build commands.
. Start up sshuttle (see the VEuPathDB confluence documentation for running a
  service locally).
. Run the target example docker container by running one of the included `make`
  run commands.
--

Example::
+
NOTE: This example assumes `sshuttle` is already running.
+
[source, shell-session]
----
$ make build-bash-example
$ make run-bash-example
----
